In [1]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance

#longitude and latitude to find in certain range
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767
desired_key="building"
Latitude1= 28.2374702
Longitude1= 83.9893031

#long and lat to find if it exist in OSM
lon11 = "{:.5f}".format(Longitude1)
lat11= "{:.5f}".format(Latitude1)

# Send the request


#to find all the buildings in certain radius
url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:1000,{lat1},{lon1})[{desired_key}];out;'

#to check whether the given coordinate with the given key exist in OSM
url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:10,{lat11},{lon11})[{desired_key}];out;'
response = requests.get(url)


# Check the response status
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Process the data
    for result in data['elements']:
        name = result.get('tags', {}).get('name', 'N/A')
        latitude = result.get('lat', 'N/A')
        longitude = result.get('lon', 'N/A')
        distance=calculate_distance(lat1, lon1, latitude, longitude)
        print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")

else:
    print(f"Request failed with status code: {response.status_code}")



# Extract the longitude and latitude from the JSON data
coordinates = []
for element in data['elements']:
    if 'lon' in element and 'lat' in element:
        coordinates.append({'latitude': element['lat'], 'longitude': element['lon']})

# Print the list of dictionaries containing longitude and latitude
# for coordinate in coordinates:
#     print(coordinate['latitude'], coordinate['longitude'])

Name: Madhavi Dental Care
Latitude: 28.2244947
Longitude: 83.9813485
 1.4105093925067627
Name: Dolphin Dental Care Center
Latitude: 28.2120516
Longitude: 83.9848158
 2.794475078290169
Name: Mata Mankamana Dental
Latitude: 28.2181893
Longitude: 83.9867026
 2.1398008423010224
Name: BB Dental Clinic
Latitude: 28.2232981
Longitude: 83.9905203
 1.7141817045573162
Name: Gandaki Dental Clinic
Latitude: 28.2233355
Longitude: 83.990384
 1.7045666286990937
Name: New Gandaki Dental Clinic
Latitude: 28.2234123
Longitude: 83.9903038
 1.693452139461426
Name: Himal Dental Clinic
Latitude: 28.2233016
Longitude: 83.9904991
 1.7129133201594624
Name: Machhapuchre Dental
Latitude: 28.2233447
Longitude: 83.9903296
 1.7013192492131015
Name: Nice Dental Care
Latitude: 28.2232189
Longitude: 83.990104
 1.7044848141961673
Name: Paropakar Dental Care Center
Latitude: 28.2233821
Longitude: 83.9901482
 1.6898958816909968
Name: The Dental Care
Latitude: 28.2232443
Longitude: 83.9907113
 1.7278940238100393
Name: Fewa Dental Clinic
Latitude: 28.2240161
Longitude: 83.9873774
 1.525275103302747
Name: Paschimanchal Dental Home
Latitude: 28.2113635
Longitude: 83.9867251
 2.889906503398963
Name: Brighter Dental
Latitude: 28.239716
Longitude: 83.9877172
 0.5644546129322734
Name: Global Dental Care
Latitude: 28.2433666
Longitude: 83.9841123
 0.7072000099513884
Name: Garima Dental Clinic
Latitude: 28.2047375
Longitude: 84.0007321
 4.007760550725822
Name: Namaste Dental Care Centre
Latitude: 28.2172837
Longitude: 83.9865104
 2.235758608109563
Name: Birauta Dental Clinic
Latitude: 28.1924925
Longitude: 83.9711226
 5.091610501041567
Name: Shyam Dental
Latitude: 28.2420038
Longitude: 83.9881523
 0.7572665424093703
Name: Perfect Dental Care
Latitude: 28.224263
Longitude: 83.9860616
 1.4653986945505408
Name: Dhaulagiri Dental Home
Latitude: 28.261074
Longitude: 83.9715489
 2.8815236589504516
Name: Amarsingh Dental Clinic
Latitude: 28.2052446
Longitude: 84.000609
 3.9518284969967143
Name: Asta Dental Clinic
Latitude: 28.2139653
Longitude: 83.9589115
 3.477117024258654
Name: Smile Care and Dential Care
Latitude: 28.2260926
Longitude: 83.9896381
 1.3986143578754082
Name: Yepolo Dental
Latitude: 28.1845465
Longitude: 84.0361941
 7.84720794942867
Name: Pokhara Shining Health and Dental Clinic
Latitude: 28.2434484
Longitude: 83.98331
 0.7059152742760082
Name: Ghandruk Dental Care
Latitude: 28.2443301
Longitude: 83.9890828
 1.012866975066772
Name: Poineer Dental Clinic
Latitude: 28.2262324
Longitude: 83.9902884
 1.4170659833803554
Name: Machhapuchchre Dental Clinic
Latitude: 28.2050653
Longitude: 83.9994277
 3.9201294953472425
Name: Metrocity Dental Clinic
Latitude: 28.2117631
Longitude: 83.9816359
 2.8215133516593367
Name: Star Dental Clinic
Latitude: 28.2115133
Longitude: 83.9668056
 3.248312854219584
Name: 32 Dental Care
Latitude: 28.1627722
Longitude: 84.0568323
 11.000992829997413
Name: Nice Dental Care Centre
Latitude: 28.2262877
Longitude: 83.9900333
 1.3989360556249932
Name: Amrit Dental Clinic
Latitude: 28.1636815
Longitude: 84.0683891
 11.708220584499152
Name: Bindabasini Dental Care
Latitude: 28.1919605
Longitude: 83.9703117
 5.167465615347653
Name: Doctor Tooth Dental Care
Latitude: 28.2240743
Longitude: 83.9900518
 1.6164714782139449
Name: Buddha Dental Care
Latitude: 28.2262448
Longitude: 83.9883746
 1.3280013725229873
Name: Birauta Dental Clinic
Latitude: 28.1924129
Longitude: 83.9711881
 5.0988051311610825
Name: Mata Manakamana Dental
Latitude: 28.1516565
Longitude: 84.0639013
 12.390636007850292
Name: Padmashree Dental Home
Latitude: 28.2194362
Longitude: 83.9866103
 2.001856181233181
Name: Doctors Dental & Implant Centre
Latitude: 28.220777
Longitude: 83.9869456
 1.8625816738163041
Name: Prime Dental Care Centre
Latitude: 28.2260667
Longitude: 83.9904638
 1.4417486297611593
Name: Dental Pokhara Care Centre
Latitude: 28.2272743
Longitude: 83.9971793
 1.7865120470597473
Name: Lotus Dental Home
Latitude: 28.2106308
Longitude: 83.9861953
 2.9643332340264505
Name: Smile Dental Care
Latitude: 28.2225911
Longitude: 83.9910493
 1.8076603524090058
Name: Subidha Dental Clinic
Latitude: 28.2092372
Longitude: 83.9851079
 3.1086754904874074
Name: Prithvi Dental Care
Latitude: 28.2078799
Longitude: 83.9836855
 3.252373612913568
Name: Brighter Dental House
Latitude: 28.2069422
Longitude: 83.9838291
 3.3570090903516947
Name: Dyanamic Dental Clinic
Latitude: 28.2098315
Longitude: 83.9855375
 3.046237979384175
Name: Himal Dental
Latitude: 28.1754549
Longitude: 84.0494978
 9.474797125344825
Name: Advance Medicine service And Dental
Latitude: 28.2128221
Longitude: 84.0097958
 3.7829900765922537
Name: Medha Dental House
Latitude: 28.2170032
Longitude: 83.9897937
 2.3402100336549148
Name: Smile Dental Care Center
Latitude: 28.2228313
Longitude: 83.9920865
 1.8322898183839662
Name: Bhadrakali Dental Clinic
Latitude: 28.2005274
Longitude: 83.9958027
 4.2644508326970225
Name: Safal Dental Clinic
Latitude: 28.2008016
Longitude: 83.9958845
 4.237793990030635
Name: Pokhara Ciy Dental
Latitude: 28.2110252
Longitude: 83.9819866
 2.9023942582015314
Name: 15 Dental
Latitude: 28.2129575
Longitude: 83.9977439
 3.0611274676794853
Name: Annapurna Dental Care
Latitude: 28.2413696
Longitude: 83.9872448
 0.6449108938535854

In [11]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance



# Send the request
url = 'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(area)["building"];out;'
response = requests.get(url)
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767

# Check the response status
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Process the data
    for result in data['elements']:
        name = result.get('tags', {}).get('name', 'N/A')
        latitude = result.get('lat', 'N/A')
        longitude = result.get('lon', 'N/A')
        distance=calculate_distance(lat1, lon1, latitude, longitude)
        print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")

else:
    print(f"Request failed with status code: {response.status_code}")

Name: New Galaxy Higher Secondary School
Latitude: 28.2285432
Longitude: 83.9907714
 1.234513241059177
Name: N/A
Latitude: 28.2374702
Longitude: 83.9893031
 0.6414876251798295
Name: Siddhartha Bank Limited
Latitude: 28.2400325
Longitude: 83.9880252
 0.6085665075711141
Name: N/A
Latitude: 28.2415624
Longitude: 83.970375
 1.3106647708614423
Name: Susovit Electric Works
Latitude: 28.2297953
Longitude: 83.985823
 0.8675417825206664
Name: Elizabeth Food Packaging Industry
Latitude: 28.221505
Longitude: 83.9819416
 1.73796862846262
Name: Shrinkhala Youth Club
Latitude: 28.2509755
Longitude: 83.9937749
 1.8807000618717415
Name: Shri Shada Shiva Subedi Samaj Ghar
Latitude: 28.2400143
Longitude: 83.9771184
 0.640239902116733
Name: Tammu Samaj Ghar
Latitude: 28.2271603
Longitude: 83.9792025
 1.1610064763936188
Name: Tripathi Sweater Industry
Latitude: 28.2305657
Longitude: 83.9838421
 0.7361557852445805

In [84]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance



# Send the request
url = 'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:2000,28.237118,83.982767)["building"];out;'
response = requests.get(url)
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767

# Check the response status
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Process the data
    for result in data['elements']:
        name = result.get('tags', {}).get('name', 'N/A')
        latitude = result.get('lat', 'N/A')
        longitude = result.get('lon', 'N/A')
        distance=calculate_distance(lat1, lon1, latitude, longitude)
        print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")

else:
    print(f"Request failed with status code: {response.status_code}")

Name: New Galaxy Higher Secondary School
Latitude: 28.2285432
Longitude: 83.9907714
 1.234513241059177
Name: N/A
Latitude: 28.2374702
Longitude: 83.9893031
 0.6414876251798295
Name: Siddhartha Bank Limited
Latitude: 28.2400325
Longitude: 83.9880252
 0.6085665075711141
Name: N/A
Latitude: 28.2415624
Longitude: 83.970375
 1.3106647708614423
Name: Susovit Electric Works
Latitude: 28.2297953
Longitude: 83.985823
 0.8675417825206664
Name: Elizabeth Food Packaging Industry
Latitude: 28.221505
Longitude: 83.9819416
 1.73796862846262
Name: Shrinkhala Youth Club
Latitude: 28.2509755
Longitude: 83.9937749
 1.8807000618717415
Name: Shri Shada Shiva Subedi Samaj Ghar
Latitude: 28.2400143
Longitude: 83.9771184
 0.640239902116733
Name: Tammu Samaj Ghar
Latitude: 28.2271603
Longitude: 83.9792025
 1.1610064763936188
Name: Tripathi Sweater Industry
Latitude: 28.2305657
Longitude: 83.9838421
 0.7361557852445805

KeyboardInterrupt: Interrupted by user

In [21]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance

latchek=float(input("Enter lat to verify:"))
longchek=float(input("Enter long to verify:"))
desired_key=input("Enter the desired key:")
min_longitude=longchek-0.00008
max_longitude=longchek+0.00008
min_latitude=latchek-0.00008
max_latitude=latchek+0.00008
# Send the request
url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node[bbox:{min_longitude},{min_latitude},{max_longitude},{max_latitude}],[key={desired_key}];out;'
#     [bbox:<min_longitude>,<min_latitude>,<max_longitude>,<max_latitude>]
#   [key=<desired_key>];out;
response = requests.get(url)
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767

# Check the response status
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Process the data
    #for result in data['elements']:
    print("This place do exist:")
    name = result.get('tags', {}).get('name', 'N/A')
    latitude = result.get('lat', 'N/A')
    longitude = result.get('lon', 'N/A')
    distance=calculate_distance(lat1, lon1, latitude, longitude)
    print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")

else:
    print(f"Request failed with status code: {response.status_code}")

# latchek=float(input("Enter lat to verify:"))
# longchek=float(input("Enter long to verify:"))
# for result in data['elements']:
#         name = result.get('tags', {}).get('name', 'N/A')
#         latitude = result.get('lat', 'N/A')
#         longitude = result.get('lon', 'N/A')
#         distance=calculate_distance(lat1, lon1, latitude, longitude)
#         if (latchek-latitude)<0.0005 and (longchek-longitude)<0.0005:
#             print("This place do exist:")
#             print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")
            


# [bbox:<min_longitude>,<min_latitude>,<max_longitude>,<max_latitude>]
#   [key=<desired_key>]

Enter lat to verify:28.2285432
Enter long to verify:83.9907714
Enter the desired key:building
Request failed with status code: 400

In [20]:

Latitude: 28.2285432
Longitude: 83.9907714

In [51]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance


lat1 = 28.23747# Latitude of first coordinate
lon1 = 83.98930
# Send the request
url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:10,{lat1},{lon1})["building"];out;'
response = requests.get(url)


# Check the response status
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Process the data
    for result in data['elements']:
        name = result.get('tags', {}).get('name', 'N/A')
        latitude = result.get('lat', 'N/A')
        longitude = result.get('lon', 'N/A')
        distance=calculate_distance(lat1, lon1, latitude, longitude)
        print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance*1000}")

else:
    print(f"Request failed with status code: {response.status_code}")

Name: N/A
Latitude: 28.2374702
Longitude: 83.9893031
 0.30449567824814594

In [40]:

lat1 = 28.23747# Latitude of first coordinate
lon1 = 83.98930
# Send the request
url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:10,{lat1},{lon1})["building"];out;'
response = requests.get(url)

data = response.json()

In [59]:
lat1 = 28.23747  # Latitude of the first coordinate
lon1 = 83.98930  # Longitude of the first coordinate

# Send the request
url = f'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:1000,{lat1},{lon1})["building"];out;'
response = requests.get(url)

data = response.json()

# Extract the longitude and latitude from the JSON data
coordinates = []
for element in data['elements']:
    if 'lon' in element and 'lat' in element:
        coordinates.append({'latitude': element['lat'], 'longitude': element['lon']})

# Print the list of dictionaries containing longitude and latitude
for coordinate in coordinates:
    print(coordinate['latitude'], coordinate['longitude'])

print (type(coordinates))

28.2374702 83.9893031
28.2400325 83.9880252
28.2297953 83.985823
28.2305657 83.9838421
<class 'list'>

In [58]:
coordinates = [
    {"latitude": 28.248767785991863, "longitude": 83.98629856004847},
    {"latitude": 28.259071283420692, "longitude": 83.9791488647461},
    {"latitude": 28.246369554498177 , "longitude": 83.98497168545931},
    {"latitude": 28.261772096881458, "longitude": 83.95889282226562},
    {"latitude": 28.230187780248816, "longitude": 84.00179002120969}
    ]
print (type(coordinates))

<class 'list'>

In [60]:
import sqlite3

In [143]:
con=sqlite3.connect("rentit.db")

In [68]:
con.execute("CREATE TABLE try (column1 text,column2 int)")

In [69]:
import pandas as pd

In [76]:
df=pd.read_sql("select * from try",con)
df.head()

  column1  column2
0      NB       12

In [81]:
con.execute("insert into Owner values ('Pokhara',28.2374702,83.9893031,'binayak@gmail.com',9807129766,'this is a very nice hjouse',1233,3)")

In [96]:
    
con.execute("create table Owner(houseloc text,latitude float,longitude float,email text,phone int,desc text,rentprice int,noroom int)")

In [82]:
room=2
df=pd.read_sql(f"select * from Owner where noroom={room}",con)
df.head()

,houseloc,latitude,longitude,email,phone,desc,rentprice,noroom
0,Pokhara,28.23747,83.989303,binayak@gmail.com,9807129766,this is a very nice hjouse,1233,2

In [90]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance



# Send the request
url = 'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:2000,28.237118,83.982767)["building"];out;'
response = requests.get(url)
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767

# # Check the response status
# if response.status_code == 200:
#     # Parse the JSON response
#     data = response.json()

#     # Process the data
#     for result in data['elements']:
#         name = result.get('tags', {}).get('name', 'N/A')
#         latitude = result.get('lat', 'N/A')
#         longitude = result.get('lon', 'N/A')
#         distance=calculate_distance(lat1, lon1, latitude, longitude)
#         print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")

# else:
#     print(f"Request failed with status code: {response.status_code}")
for i in data['elements']:
    print(i)

{'type': 'node', 'id': 3114505717, 'lat': 28.2285432, 'lon': 83.9907714, 'tags': {'building': 'school', 'name': 'New Galaxy Higher Secondary School', 'name:ne': 'नयां ग्यालेक्सी उच्च मा. वि.'}}
{'type': 'node', 'id': 4160825769, 'lat': 28.2374702, 'lon': 83.9893031, 'tags': {'building': 'residential'}}
{'type': 'node', 'id': 4798636097, 'lat': 28.2400325, 'lon': 83.9880252, 'tags': {'addr:city': 'Pokhara', 'addr:street': 'Bagar', 'amenity': 'bank', 'building': 'yes', 'name': 'Siddhartha Bank Limited', 'name:ne': 'सिद्धार्थ बैंक लिमिटेड', 'nrb_class': 'commercial', 'operator': 'Siddhartha Bank Limited', 'phone': '061-527747,527748', 'source': '2cpokhara', 'website': 'www.siddharthabank.com'}}
{'type': 'node', 'id': 5049150382, 'lat': 28.2415624, 'lon': 83.970375, 'tags': {'building': 'yes'}}
{'type': 'node', 'id': 5415607033, 'lat': 28.2297953, 'lon': 83.985823, 'tags': {'addr:city': 'pokhahra', 'addr:street': 'Tersapatti Road', 'building': 'yes', 'description': 'Susovit Electric Works', 'name': 'Susovit Electric Works'}}
{'type': 'node', 'id': 5453980077, 'lat': 28.221505, 'lon': 83.9819416, 'tags': {'building': 'Factory', 'name': 'Elizabeth Food Packaging Industry', 'source': '2c pokhara'}}
{'type': 'node', 'id': 5470403011, 'lat': 28.2509755, 'lon': 83.9937749, 'tags': {'building': 'yes', 'name': 'Shrinkhala Youth Club', 'source': '2cpokhara'}}
{'type': 'node', 'id': 5488272932, 'lat': 28.2400143, 'lon': 83.9771184, 'tags': {'amenity': 'events_venue', 'building': 'yes', 'name': 'Shri Shada Shiva Subedi Samaj Ghar'}}
{'type': 'node', 'id': 5504193916, 'lat': 28.2271603, 'lon': 83.9792025, 'tags': {'amenity': 'events_venue', 'building': 'yes', 'name': 'Tammu Samaj Ghar'}}
{'type': 'node', 'id': 5509775783, 'lat': 28.2305657, 'lon': 83.9838421, 'tags': {'building': 'yes', 'contact:phone': '9846263250 (Jeevan) 984633631187 (Nabaraj) 9804195739(Bikram)', 'name': 'Tripathi Sweater Industry', 'opening_hours': 'sunrise-sunset'}}

In [149]:
import requests
import json
import math

def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance



# Send the request
url = 'https://overpass-api.de/api/interpreter?data=[out:json];area[name="Pokhara"];node(around:2000,28.237118,83.982767)["building"];out;'
response = requests.get(url)
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767

# Check the response status
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()

    # Process the data
    for result in data['elements']:
        name = result.get('tags', {}).get('name', 'N/A')
        latitude = result.get('lat', 'N/A')
        longitude = result.get('lon', 'N/A')
        distance=calculate_distance(lat1, lon1, latitude, longitude)
        print(f"Name: {name}\nLatitude: {latitude}\nLongitude: {longitude}\n {distance}")
        con.execute(f"insert into Owner values ('Pokhara',{longitude},{latitude},'binayak@gmail.com',9807129766,'this is a very nice hjouse',1233,3)")

else:
    print(f"Request failed with status code: {response.status_code}")

Name: New Galaxy Higher Secondary School
Latitude: 28.2285432
Longitude: 83.9907714
 1.234513241059177
Name: N/A
Latitude: 28.2374702
Longitude: 83.9893031
 0.6414876251798295
Name: Siddhartha Bank Limited
Latitude: 28.2400325
Longitude: 83.9880252
 0.6085665075711141
Name: N/A
Latitude: 28.2415624
Longitude: 83.970375
 1.3106647708614423
Name: Susovit Electric Works
Latitude: 28.2297953
Longitude: 83.985823
 0.8675417825206664
Name: Elizabeth Food Packaging Industry
Latitude: 28.221505
Longitude: 83.9819416
 1.73796862846262
Name: Shrinkhala Youth Club
Latitude: 28.2509755
Longitude: 83.9937749
 1.8807000618717415
Name: Shri Shada Shiva Subedi Samaj Ghar
Latitude: 28.2400143
Longitude: 83.9771184
 0.640239902116733
Name: Tammu Samaj Ghar
Latitude: 28.2271603
Longitude: 83.9792025
 1.1610064763936188
Name: Tripathi Sweater Industry
Latitude: 28.2305657
Longitude: 83.9838421
 0.7361557852445805

In [148]:
df=pd.read_sql("select * from Owner",con)
df

Empty DataFrame
Columns: [houseloc, latitude, longitude, email, phone, desc, rentprice, noroom]
Index: []

In [94]:
con.execute("drop table Owner")
con.commit()

In [130]:
def calculate_distance(lat1, lon1, lat2, lon2):
    # Convert decimal degrees to radians
    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    # Haversine formula
    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    # Radius of the Earth in kilometers
    radius = 6371

    # Calculate the distance
    distance = radius * c

    return distance

print(calculate_distance(28.0068,83.0068,28.000000,83.000000))
print(calculate_distance(28.2271603+0.0068,83.9792025+0.0068,28.237118,83.982767))
print(calculate_distance(28.2271603,83.9792025,28.237118,83.982767))

1.0086689392858472
0.4730225837109628
1.1610064763936188

In [136]:
lat1 = 28.237118# Latitude of first coordinate
lon1 = 83.982767
df=pd.read_sql(f"select * from Owner where {6371*2*math.asin(math.sqrt(pow(math.sin((math.radians(latitude) - math.radians(lat1)) / 2), 2) +math.cos(math.radians(lat1)) * math.cos({math.radians(latitude)})*pow(math.sin((math.radians(longitude) - math.radians(lon1))/ 2), 2)))} <= 1",con)
df

TypeError: must be real number, not set

In [137]:
lat=12
print(f"{2*math.sqrt(lat*12)}")

24.0

In [139]:
con.execute("select * from Owner")
df=curs
#result = cursor.fetchall()

In [154]:
cursor=con.cursor()
query = "SELECT longitude FROM Owner limit 1"
cursor.execute(query)

# Fetch the result and assign it to a variable
result = cursor.fetchall()

# Close the cursor and the connection
cursor.close()
print(type(result))
for i in result:
    print(i)

<class 'list'>
(28.2285432,)